import type { Categoria, Pieza } from '../trabajo'

export const trabajo: Pieza[] = [
  {
    id: 'crm-tadi',
    titulo: 'CRM TADI',
    categoria: 'Aplicación',
    restringido: 'Restricted access · internal system',
    captura: 'crm-tadi',
    galeria: [
      { archivo: 'crm-panel', pie: 'Dashboard with live data' },
      { archivo: 'crm-oportunidades', pie: 'A 7,498-case pipeline, draggable between stages' },
      { archivo: 'crm-tareas', pie: 'Task board grouped by due date' },
      { archivo: 'crm-chat', pie: 'Internal chat with file sharing and video calls' },
      { archivo: 'crm-asistencia', pie: 'Team time tracking' },
    ],
    color: 'azul',
    año: '2026',
    gancho: 'The company CRM. I built it from scratch and the whole team now uses it every day.',
    detalle: [
      'A monorepo with three applications: a React and Next.js frontend, an Express and TypeScript API, and a Python AI service. Six independent processes in production, with the mail worker and the follow-up agent isolated on purpose so a mail server hiccup cannot take the API down.',
      'On an 85-table PostgreSQL database: 7,498 opportunities in the pipeline, 3,811 active contacts — 31,622 contact records in total counting the imported history — 39,032 tasks and 196,818 indexed files. In-house video calls with LiveKit, mailbox sync and document management on Cloudflare R2.',
      'It also meant consolidating three legacy CRMs — Pipedrive, Bitrix24 and Zoho — into the new model while the system stayed in use: cross-platform deduplication with reversible merges, custom fields with no equivalent, and an import log for every pass.',
    ],
    cifras: [
      { n: '85', que: 'tables' },
      { n: '7,498', que: 'opportunities' },
      { n: '243', que: 'commits' },
    ],
    stack: ['React', 'Next.js', 'TypeScript', 'Express', 'FastAPI', 'PostgreSQL', 'LiveKit', 'Cloudflare R2'],
  },
  {
    id: 'web-corporativa',
    titulo: 'Tu Agente de Inmigración',
    categoria: 'Web corporativa',
    url: 'https://tuagentedeinmigracion.org',
    captura: 'web-corporativa',
    color: 'verde',
    año: '2026',
    gancho: 'The company website. Next.js, served from the VPS I administer myself.',
    detalle: [
      'The main shopfront of the business: immigration services, social proof and WhatsApp capture. Built in Next.js and deployed with PM2 behind nginx, on the server I run.',
      'The contact form does not die in an inbox: it fires a webhook into the automation chain and creates the contact in the CRM with its attribution intact.',
    ],
    cifras: [
      { n: 'Next.js', que: 'on my own VPS' },
      { n: '+426', que: 'families served' },
    ],
    stack: ['Next.js', 'React', 'nginx', 'PM2', 'n8n'],
  },
  {
    id: 'ciudadania',
    titulo: 'US Citizenship',
    categoria: 'Landing de captación',
    url: 'https://ciudadania.tuagentedeinmigracion.com',
    captura: 'ciudadania',
    color: 'amarillo',
    año: '2026',
    gancho: 'Landing page for the citizenship course: captures the lead and hands it to the calendar.',
    detalle: [
      'A capture page with the full funnel: the offer, social proof, a qualification form and the handoff to the sales calendar.',
      'Ad attribution survives the whole journey — `_fbp`, `_fbc`, UTM and `fbclid` — so the ad spend can actually be measured.',
    ],
    cifras: [
      { n: 'Next.js 16', que: 'in production' },
      { n: '0', que: 'process restarts' },
    ],
    stack: ['Next.js', 'React', 'PostgreSQL', 'Meta CAPI'],
  },
  {
    id: 'feedecorte',
    titulo: 'Court Fee Guide',
    categoria: 'Landing de captación',
    url: 'https://feedecorte.tuagentedeinmigracion.com',
    captura: 'feedecorte',
    color: 'amarillo',
    año: '2026',
    gancho: 'Landing page delivering a PDF guide, wired to the WhatsApp agent that picks up the lead.',
    detalle: [
      'I ask for the phone number twice on purpose: a mistyped number turns a paid lead into garbage and there is no way to recover it.',
      'On sign-up the visitor gets the guide as a native WhatsApp document through an approved template, and lands in a conversation with the automated agent.',
      'I added preview parameters so the client can review the page without their own visits registering as leads or polluting the metrics.',
    ],
    cifras: [
      { n: '2×', que: 'phone confirmation' },
      { n: '186', que: 'nodes in the agent behind it' },
    ],
    stack: ['Next.js', 'TypeScript', 'n8n', 'GoHighLevel', 'PostgreSQL'],
  },
  {
    id: 'link-bio',
    titulo: 'Link-in-bio page',
    categoria: 'Aplicación',
    url: 'https://link.tuagentedeinmigracion.com',
    captura: 'link-bio',
    color: 'gris',
    año: '2026',
    gancho: 'Where the brand’s Instagram link lands: it routes traffic across services and channels.',
    detalle: [
      'A static site served by nginx with a 30-day image cache. Small, but it is the door the brand’s social traffic comes through.',
    ],
    cifras: [{ n: '30 d', que: 'image cache' }],
    stack: ['HTML', 'CSS', 'nginx'],
  },
  {
    id: 'contacto-vcard',
    titulo: 'Digital business card',
    categoria: 'Aplicación',
    url: 'https://contacto.tuagentedeinmigracion.com',
    captura: 'contacto-vcard',
    color: 'gris',
    año: '2026',
    gancho: 'A digital business card that saves straight into the visitor’s phone.',
    detalle: [
      'I serve the `.vcf` file with the correct MIME type, so the phone offers to save the contact instead of downloading a loose file. A small detail that decides whether it works at all.',
    ],
    cifras: [{ n: 'vCard', que: 'correct MIME type' }],
    stack: ['HTML', 'CSS', 'nginx'],
  },
  {
    id: 'paula-manhattan',
    titulo: '«Paula» WhatsApp agents',
    categoria: 'Automatización',
    restringido: 'Internal system · no public interface',
    captura: 'n8n-setter',
    galeria: [
      { archivo: 'n8n-setter', pie: 'The agent with its tools and the five outputs to the CRM' },
      { archivo: 'n8n-seguros-inbound', pie: 'Inbound, cadence cut, courtesy reply and operator alert' },
      { archivo: 'n8n-paula-manhattan', pie: 'The Manhattan conversational flow, published' },
      { archivo: 'n8n-seguimiento-scan', pie: 'The follow-up probe, every 15 minutes' },
      { archivo: 'n8n-extra', pie: 'One of the supporting flows' },
    ],
    color: 'verde',
    año: '2026',
    gancho:
      'Four agents that greet, qualify and book leads. Seven flows are still live in production.',
    detalle: [
      'The state machine does not live in the code: it lives in the database, with foreign keys, so a step that is not in the design cannot even be written.',
      'The AI layer is hybrid and sits alongside a deterministic script: a cheap model classifies, a better one writes, and the business logic never lives in the prompt. It shipped in shadow mode — running in parallel with no ability to act — until there was data on whether it was right.',
      'If the AI fails or the quota runs out, the agent keeps working from the script. Verified in 10 out of 10 cases.',
    ],
    cifras: [
      { n: '7', que: 'live flows' },
      { n: '13 / 25', que: 'steps and transitions' },
      { n: '37 + 8', que: 'tests, zero failures' },
    ],
    stack: ['n8n', 'PostgreSQL', 'Vertex AI', 'Gemini 2.5', 'GoHighLevel'],
  },
  {
    id: 'ghl',
    titulo: 'GoHighLevel automation',
    categoria: 'Automatización',
    restringido: 'Commercial CRM · restricted access',
    captura: 'ghl-sistema-ventas',
    galeria: [
      { archivo: 'ghl-sistema-ventas', pie: 'Sales system: three triggers and nine branches by stage' },
      { archivo: 'ghl-seguimientos', pie: 'Follow-up system, with a cleanup step on every branch' },
      { archivo: 'ghl-puente-n8n', pie: 'The bridge to n8n, published and filtered by tag' },
      { archivo: 'ghl-envio-api', pie: 'Conversion event sent to the Meta API' },
      { archivo: 'ghl-membresia-bot', pie: 'From the membership landing to the bot and the pipeline' },
      { archivo: 'ghl-extra-1', pie: 'Another flow in production' },
      { archivo: 'ghl-extra-2', pie: 'Another flow in production' },
    ],
    color: 'azul',
    año: '2026',
    gancho:
      'The commercial layer connecting the ads, the bots and the human team. 22 endpoints in use and 12 n8n flows hanging off it.',
    detalle: [
      'Contact tags are not categories here: they are the engine. Someone on the team adds a tag from the panel and that fires a webhook which activates a payment plan, generates eight instalments and unlocks course access. It is an operations interface for people who do not touch code.',
      'The bridge to the bots took a while to switch on because of an asymmetry that is hard to see: messages went out through an external provider and came back in as custom-provider SMS, not as WhatsApp, so the trigger never fired. It was solved by capturing a real payload instead of assuming the interface vocabulary matched the API vocabulary.',
      'The bridge trigger had no filters and racked up 1,197 paid executions, many for messages that did not need processing. Filtering it by tag is the difference between an integration and an invoice.',
      'Its rate limit forced building a gateway of our own in Node, Express and Redis, which queues and prioritises: anything answering a waiting customer always gets through; background polling waits.',
    ],
    cifras: [
      { n: '22', que: 'endpoints in use' },
      { n: '12', que: 'n8n flows connected' },
      { n: '17', que: 'inbound webhooks' },
    ],
    stack: ['GoHighLevel', 'n8n', 'Meta CAPI', 'Node.js', 'Redis', 'PostgreSQL'],
  },
  {
    id: 'arnes',
    titulo: 'Design-conformance harness',
    categoria: 'Herramienta',
    restringido: 'Internal quality tool',
    motivo: 'arnes',
    color: 'rojo',
    año: '2026',
    gancho:
      'It checks by itself that the software I build matches its design diagram, in three directions.',
    detalle: [
      'Box with no node (designed and never built), node with no box (built and not in the design), and edge with no connection (the diagram’s route does not exist). It exits non-zero when they diverge, so it drops straight into a pipeline.',
      'I validated it by breaking it on purpose across four failure modes, because a check that has never failed is not validated — it is just unused. On its first run it found two faults in itself and one real drift.',
    ],
    cifras: [
      { n: '3', que: 'directions checked' },
      { n: '4', que: 'failure modes tested' },
    ],
    stack: ['Python', 'JSON', 'CI'],
  },
  {
    id: 'medicare',
    titulo: 'Medicare questionnaire',
    categoria: 'Landing de captación',
    url: 'https://juanmanueltuagente.com',
    pendiente: true,
    restringido: 'Pending promotion to production',
    captura: 'medicare',
    galeria: [
      { archivo: 'medicare-1', pie: 'Opening: licensed agent, two minutes, no commitment' },
      { archivo: 'medicare-3', pie: 'Question 1 of 11 — health conditions' },
      { archivo: 'medicare-2', pie: 'The three steps and the required Medicare disclaimer' },
    ],
    color: 'amarillo',
    año: '2026',
    gancho:
      'An eleven-question qualifier over a 207-plan catalogue, with ZIP-code-to-county geocoding.',
    detalle: [
      'Eleven questions with qualification logic over 18 tables and 207 loaded plans, plus geocoding from ZIP code to county to work out what applies in each area.',
      'ZIP validation has three states, not two: valid, non-existent and unverifiable. On the third I let the user through. If the geocoder goes down the form does not block — the comfortable alternative would have lost leads silently.',
      'The questionnaire avatar is an SVG component I wrote by hand, around 7 KB, where every piece is an animatable node and there is not a single external request.',
    ],
    cifras: [
      { n: '18', que: 'tables · 207 plans' },
      { n: '11', que: 'questions' },
      { n: '7 KB', que: 'the SVG avatar' },
    ],
    stack: ['Next.js', 'TypeScript', 'React', 'PostgreSQL', 'SVG', 'Meta CAPI'],
  },
  {
    id: 'manhattan',
    titulo: 'ManhattanLife',
    categoria: 'Landing de captación',
    url: 'https://juanmanueltuagente.com',
    pendiente: true,
    restringido: 'Pending promotion to production',
    captura: 'manhattan',
    galeria: [
      { archivo: 'manhattan-1', pie: '«Let me understand your case» before recommending anything' },
      { archivo: 'manhattan-3', pie: 'A verifiable Florida licence — not a promise' },
      { archivo: 'manhattan-4', pie: 'The qualification questionnaire, step by step' },
      { archivo: 'manhattan-2', pie: 'How it works, in three steps' },
    ],
    color: 'amarillo',
    año: '2026',
    gancho:
      'A health-insurance landing page and questionnaire, built in three days and wired to the agent that picks up the lead.',
    detalle: [
      'Landing page, questionnaire and animated SVG avatar in three days, with a responsive audit verified at 320, 390 and 1280 pixels until it came back clean.',
      'The Google reviews sit inside a modal instead of linking away: the visitor sees the social proof and does not abandon the page the company just paid for.',
      'Once the landing was done I went to look at what happened after the form, and found two things nobody had asked me to check: the chain was broken — data reached the database and stopped there — and an automatic purge deleted unprocessed records after 72 hours. Any lead arriving on a Friday vanished by Monday.',
    ],
    cifras: [
      { n: '3', que: 'days to build' },
      { n: '16', que: 'tables' },
      { n: '19', que: 'hand-drawn SVG flags' },
    ],
    stack: ['Next.js', 'TypeScript', 'React', 'PostgreSQL', 'SVG', 'Meta CAPI'],
  },
  {
    id: 'infraestructura',
    titulo: 'Infrastructure & DevOps',
    categoria: 'Herramienta',
    restringido: 'Production server',
    motivo: 'infraestructura',
    color: 'rojo',
    año: '2026',
    gancho:
      'I run the server everything above lives on. Two critical migrations, with no data loss.',
    detalle: [
      'Ubuntu Server with 29 containers, 19 processes and 22 domains under TLS. nginx as reverse proxy, PM2 for the Node processes, certbot for the certificates.',
      'I migrated n8n from SQLite to PostgreSQL with two minutes of downtime: I did not repair the third corruption, I removed its cause. And I moved version control from a self-hosted Gitea to GitHub, with a new CI/CD pipeline.',
      'The diagnosis I am proudest of: nginx answered on two domains but the TLS certificate only covered one. The external platform validated TLS, dropped the connection, and left no trace in any log. That was the real reason 54 executions never arrived.',
    ],
    cifras: [
      { n: '29', que: 'containers' },
      { n: '22', que: 'domains under TLS' },
      { n: '2 min', que: 'downtime in the migration' },
    ],
    stack: ['Ubuntu', 'Docker', 'nginx', 'certbot', 'PM2', 'GitHub Actions'],
  },
  {
    id: 'biblioteca',
    titulo: 'n8n engineering library',
    categoria: 'Documentación',
    restringido: 'Internal documentation',
    motivo: 'biblioteca',
    color: 'gris',
    año: '2026',
    gancho:
      '18 technical documents put through a reviewer whose job was to refute my own conclusions.',
    detalle: [
      'Around 600 KB of documentation with 231 cited sources, which I wrote using multi-agent research. I set an adversarial reviewer on my own conclusions: it knocked down five claims before I published them, including a deprecation I had taken as fact.',
      'In the most ambitious document I reviewed 107 conversational agents and 25 primary sources to settle the agent architecture, and wrote down the compliance framework that applies: WhatsApp’s policy on open-ended assistants, and the precedent that the company is liable for whatever its bot says.',
    ],
    cifras: [
      { n: '18', que: 'documents' },
      { n: '231', que: 'sources' },
      { n: '5', que: 'claims refuted' },
    ],
    stack: ['Multi-agent research', 'Adversarial review'],
  },
]

export const categorias: Categoria[] = [
  'Web corporativa',
  'Landing de captación',
  'Aplicación',
  'Automatización',
  'Herramienta',
  'Documentación',
]

/** Category labels in English, keyed by the Spanish enum. */
export const etiquetaCategoria: Record<Categoria, string> = {
  'Web corporativa': 'Company website',
  'Landing de captación': 'Lead-capture page',
  'Aplicación': 'Application',
  'Automatización': 'Automation',
  'Herramienta': 'Tooling',
  'Documentación': 'Documentation',
}
